# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 02:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pwd',
            field=models.CharField(default=123, max_length=16),
            preserve_default=False,
        ),
    ]
